/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package threadrelay;

/**
 *
 * @author Diego
 */
import java.awt.*;
import javax.swing.*;

public class RelayRunForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RelayRunForm.class.getName());
    public static int posAttuale;
    private Runner[] runners;
    private JProgressBar[] barre;
    private boolean pausa;

    /**
     * Creates new form RelayRunForm
     */
    public RelayRunForm() {
        initComponents();
        
        pgbThread1 = sostituisciProgressBar(pgbThread1);
        pgbThread2 = sostituisciProgressBar(pgbThread2);
        pgbThread3 = sostituisciProgressBar(pgbThread3);
        pgbThread4 = sostituisciProgressBar(pgbThread4);
        
        this.runners = new Runner[4];
        this.barre = new JProgressBar[4];
        this.pausa = false;
        this.posAttuale = 0;
    }
    
    private JProgressBar sostituisciProgressBar(JProgressBar vecchia) {
        BarraRunner nuova = new BarraRunner();
        nuova.setFont(vecchia.getFont());
        nuova.setMinimum(vecchia.getMinimum());
        nuova.setMaximum(vecchia.getMaximum());
        nuova.setValue(0);
 
        Container parent = vecchia.getParent();
        Component[] figli = parent.getComponents();
        for (int i = 0; i < figli.length; i++) {
            if (figli[i] == vecchia) {
                parent.remove(i);
                parent.add(nuova, i);
                break;
            }
        }
        parent.revalidate();
        parent.repaint();
        return nuova;
    }
    
    private double trovaVelocita() {
        switch ((String) spSpeed.getValue()) {
            case "Slow":    return 1.0;
            case "Regular": return 1.5;
            case "Fast": return 2.5;
            default:        return 7;
        }
    }
    
    private void iniziaGara() {
        barre[0] = pgbThread1;
        barre[1] = pgbThread2;
        barre[2] = pgbThread3;
        barre[3] = pgbThread4;
        
        double velocita = trovaVelocita();
        
        for (int i = 0; i < 4; i++) {
            runners[i] = new Runner(barre[i], velocita, i);
            Thread t = new Thread(runners[i]);
            t.start();
        }
    }
    
    private void pausaGara() {
        for (Runner r : runners) {
            r.setInPausa(true);
        }
    }
    
    private void riprendiGara() {
        for (Runner r : runners) {
            r.riprendi();
        }
    }
    
    private void fermaGara() {
        pausaGara();
        for (int i = 0; i < 4; i++) {
            runners[i] = null;
            barre[i].setValue(0);
            barre[i].setString("0%");
        }
        posAttuale = 0;
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitolo = new javax.swing.JPanel();
        lblTitolo = new javax.swing.JLabel();
        pnlCentro = new javax.swing.JPanel();
        pnlThread = new javax.swing.JPanel();
        pgbThread1 = new javax.swing.JProgressBar();
        pgbThread2 = new javax.swing.JProgressBar();
        pgbThread3 = new javax.swing.JProgressBar();
        pgbThread4 = new javax.swing.JProgressBar();
        pnlInfo = new javax.swing.JPanel();
        pnlThread1 = new javax.swing.JPanel();
        lblThread1 = new javax.swing.JLabel();
        pnlThread2 = new javax.swing.JPanel();
        lblThread2 = new javax.swing.JLabel();
        pnlThread3 = new javax.swing.JPanel();
        lblThread3 = new javax.swing.JLabel();
        pnlThread4 = new javax.swing.JPanel();
        lblThread4 = new javax.swing.JLabel();
        pnlOpzioni = new javax.swing.JPanel();
        spSpeed = new javax.swing.JSpinner();
        btnAvvia = new javax.swing.JButton();
        btnSospende = new javax.swing.JButton();
        btnRiprende = new javax.swing.JButton();
        btnTermina = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thread Relay");
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 500));

        pnlTitolo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlTitolo.setLayout(new java.awt.BorderLayout());

        lblTitolo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitolo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitolo.setText("Relay Runners");
        pnlTitolo.add(lblTitolo, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlTitolo, java.awt.BorderLayout.PAGE_START);

        pnlCentro.setLayout(new java.awt.BorderLayout());

        pnlThread.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlThread.setPreferredSize(new java.awt.Dimension(700, 539));
        pnlThread.setLayout(new java.awt.GridLayout(4, 1, 10, 20));

        pgbThread1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        pgbThread1.setStringPainted(true);
        pnlThread.add(pgbThread1);

        pgbThread2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        pgbThread2.setStringPainted(true);
        pnlThread.add(pgbThread2);

        pgbThread3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        pgbThread3.setStringPainted(true);
        pnlThread.add(pgbThread3);

        pgbThread4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        pgbThread4.setStringPainted(true);
        pnlThread.add(pgbThread4);

        pnlCentro.add(pnlThread, java.awt.BorderLayout.CENTER);

        pnlInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlInfo.setMinimumSize(new java.awt.Dimension(100, 200));
        pnlInfo.setPreferredSize(new java.awt.Dimension(200, 539));
        pnlInfo.setLayout(new java.awt.GridLayout(4, 1, 10, 20));

        pnlThread1.setBackground(new java.awt.Color(181, 209, 236));
        pnlThread1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlThread1.setLayout(new java.awt.BorderLayout());

        lblThread1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblThread1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThread1.setText("Runner 1");
        pnlThread1.add(lblThread1, java.awt.BorderLayout.CENTER);

        pnlInfo.add(pnlThread1);

        pnlThread2.setBackground(new java.awt.Color(181, 209, 236));
        pnlThread2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlThread2.setLayout(new java.awt.BorderLayout());

        lblThread2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblThread2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThread2.setText("Runner 2");
        pnlThread2.add(lblThread2, java.awt.BorderLayout.CENTER);

        pnlInfo.add(pnlThread2);

        pnlThread3.setBackground(new java.awt.Color(181, 209, 236));
        pnlThread3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlThread3.setLayout(new java.awt.BorderLayout());

        lblThread3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblThread3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThread3.setText("Runner 3");
        pnlThread3.add(lblThread3, java.awt.BorderLayout.CENTER);

        pnlInfo.add(pnlThread3);

        pnlThread4.setBackground(new java.awt.Color(181, 209, 236));
        pnlThread4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        pnlThread4.setLayout(new java.awt.BorderLayout());

        lblThread4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        lblThread4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThread4.setText("Runner 4");
        pnlThread4.add(lblThread4, java.awt.BorderLayout.CENTER);

        pnlInfo.add(pnlThread4);

        pnlCentro.add(pnlInfo, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlOpzioni.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 50, 10, 50));
        pnlOpzioni.setPreferredSize(new java.awt.Dimension(900, 75));
        pnlOpzioni.setLayout(new java.awt.GridLayout(1, 4, 50, 50));

        spSpeed.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        spSpeed.setModel(new javax.swing.SpinnerListModel(new String[] {"Slow", "Regular", "Fast", "Very Fast"}));
        spSpeed.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                spSpeedVetoableChange(evt);
            }
        });
        pnlOpzioni.add(spSpeed);

        btnAvvia.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnAvvia.setText("Avvia");
        btnAvvia.setPreferredSize(new java.awt.Dimension(100, 30));
        btnAvvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvviaActionPerformed(evt);
            }
        });
        pnlOpzioni.add(btnAvvia);

        btnSospende.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnSospende.setText("Sospende");
        btnSospende.setEnabled(false);
        btnSospende.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSospende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSospendeActionPerformed(evt);
            }
        });
        pnlOpzioni.add(btnSospende);

        btnRiprende.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRiprende.setText("Riprende");
        btnRiprende.setEnabled(false);
        btnRiprende.setPreferredSize(new java.awt.Dimension(100, 30));
        btnRiprende.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiprendeActionPerformed(evt);
            }
        });
        pnlOpzioni.add(btnRiprende);

        btnTermina.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnTermina.setText("Termina");
        btnTermina.setEnabled(false);
        btnTermina.setPreferredSize(new java.awt.Dimension(100, 30));
        btnTermina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminaActionPerformed(evt);
            }
        });
        pnlOpzioni.add(btnTermina);

        getContentPane().add(pnlOpzioni, java.awt.BorderLayout.PAGE_END);

        getAccessibleContext().setAccessibleName("RelayRunForm");

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void btnAvviaActionPerformed(java.awt.event.ActionEvent evt) {
        iniziaGara();
        btnAvvia.setEnabled(false);
        btnSospende.setEnabled(true);
        btnTermina.setEnabled(true);
    }
     
     private void btnSospendeActionPerformed(java.awt.event.ActionEvent evt) {
        pausaGara();
        btnSospende.setEnabled(false);
        btnRiprende.setEnabled(true);
     }
    private void btnRiprendeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiprendeActionPerformed
        riprendiGara();
        btnRiprende.setEnabled(false);
        btnSospende.setEnabled(true);
    }//GEN-LAST:event_btnRiprendeActionPerformed

    private void btnTerminaActionPerformed(java.awt.event.ActionEvent evt) {
        fermaGara();
        btnAvvia.setEnabled(true);
        btnSospende.setEnabled(false);
        btnRiprende.setEnabled(false);
        btnTermina.setEnabled(false);
    }
    private void spSpeedVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_spSpeedVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_spSpeedVetoableChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RelayRunForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvvia;
    private javax.swing.JButton btnRiprende;
    private javax.swing.JButton btnSospende;
    private javax.swing.JButton btnTermina;
    private javax.swing.JLabel lblThread1;
    private javax.swing.JLabel lblThread2;
    private javax.swing.JLabel lblThread3;
    private javax.swing.JLabel lblThread4;
    private javax.swing.JLabel lblTitolo;
    private javax.swing.JProgressBar pgbThread1;
    private javax.swing.JProgressBar pgbThread2;
    private javax.swing.JProgressBar pgbThread3;
    private javax.swing.JProgressBar pgbThread4;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JPanel pnlOpzioni;
    private javax.swing.JPanel pnlThread;
    private javax.swing.JPanel pnlThread1;
    private javax.swing.JPanel pnlThread2;
    private javax.swing.JPanel pnlThread3;
    private javax.swing.JPanel pnlThread4;
    private javax.swing.JPanel pnlTitolo;
    private javax.swing.JSpinner spSpeed;
    // End of variables declaration//GEN-END:variables
}
